# Generated by Django 6.0.3 on 2026-10-02 00:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.PositiveSmallIntegerField(null=True)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.CharField(max_length=255, null=True)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('claimed_by', 'key'), name='idempotency_by_reference_idempotencyclaim_key')],
            },
        ),
    ]
