# Generated by Django 6.0.3 on 2026-10-02 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyClaim',
            fields=[
                ('id', models.BigAutoField(db_comment="The claim's own identifier.", help_text="The claim's own identifier.", primary_key=True, serialize=False)),
                ('key', models.UUIDField(db_comment='The Idempotency-Key the caller sent.', help_text='The Idempotency-Key the caller sent.')),
                ('fingerprint', models.CharField(db_comment='sha256 of the request the key was spent on - its method, path, query and body.', help_text='sha256 of the request the key was spent on - its method, path, query and body.', max_length=64)),
                ('status', models.PositiveSmallIntegerField(db_comment='The status the request was answered with. Null only while its request is being served.', help_text='The status the request was answered with.', null=True)),
                ('claimed_at', models.DateTimeField(db_comment='When the key was spent. Nothing expires by it - it is there to delete old claims by.', default=django.utils.timezone.now, help_text='When the key was spent.')),
                ('object_id', models.CharField(db_comment='The primary key of the row the response serialized - null for a response without a body.', help_text='The primary key of the row the response serialized, to serialize it again.', max_length=255, null=True)),
                ('claimed_by', models.ForeignKey(db_comment="Who spent the key - a key is only ever compared with its caller's own.", help_text="Who spent the key - a key is only ever compared with its caller's own.", on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('claimed_by', 'key'), name='idempotency_by_reference_idempotencyclaim_key')],
            },
        ),
    ]
