"""
Builds `isik/locale/isik.pot` - every message isik marks for translation, in the template format
translators and `msgmerge` work from. Regenerate after adding or changing one:

    python -m tests.translation_catalog

`test_translations.py` fails when the committed catalog is out of date, and when a user-facing string
bypasses isik._internal.translation - so a message can't be added without being translatable.
"""

import ast
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
PACKAGE = ROOT / "isik"
CATALOG = PACKAGE / "locale" / "isik.pot"
# stdlib's HTTPStatus descriptions, which http_exceptions translates when it renders them - fixed data
# rather than read from the running Python, since they differ between versions (3.13 reworded some,
# 3.14 added more) and the catalog has to come out the same on every one CI runs. The union across
# every supported version; test_translations checks the running Python's are all here.
HTTP_STATUS_DESCRIPTIONS = (
    "Bad request syntax or unsupported method",
    "Cannot fulfill request",
    "Cannot satisfy request range",
    "Clear input form for further input",
    "Client must specify Content-Length",
    "Content is too large",
    "Dependent action of the request failed",
    "Document created, URL follows",
    "Document has not changed since given time",
    "Entity body in unsupported format",
    "Entity is too large",
    "Expect condition could not be satisfied",
    "Headers sent to prepare for the response",
    "Invalid responses from another server/proxy",
    "No payment -- see charging schemes",
    "No permission -- see authorization schemes",
    "Nothing matches the given URI",
    "Object has several resources -- see URI list",
    "Object moved -- see Method and URL list",
    "Object moved permanently -- see URI list",
    "Object moved temporarily -- see URI list",
    "Operation has already been reported",
    "Partial content follows",
    "Precondition in headers is false",
    "Request accepted, processing continues off-line",
    "Request completed using instance manipulations",
    "Request conflict",
    "Request does not meet the resource access policy",
    "Request forbidden -- authorization will not help",
    "Request fulfilled from cache",
    "Request fulfilled, document follows",
    "Request fulfilled, nothing follows",
    "Request received, please continue",
    "Request timed out; try again later",
    "Resource of a method is locked",
    "Response contains multiple statuses in the body",
    "Server does not support this operation",
    "Server encountered an infinite loop while processing a request",
    "Server got itself in trouble",
    "Server has an internal configuration error",
    "Server is not able to process the contained instructions",
    "Server is not able to produce a response",
    "Server is not able to store the representation",
    "Server is processing the request",
    "Server refuses to brew coffee because it is a teapot",
    "Server refuses to brew coffee because it is a teapot.",
    "Server refuses to perform the request using the current protocol",
    "Server refuses to process a request that might be replayed",
    "Specified method is invalid for this resource",
    "Switching to new protocol; obey Upgrade header",
    "The client needs to authenticate to gain network access",
    "The gateway server did not receive a timely response",
    "The origin server requires the request to be conditional",
    "The server cannot process the request due to a high load",
    "The server is denying access to the resource as a consequence of a legal demand",
    "The server is unwilling to process the request because its header fields are too large",
    'The user has sent too many requests in a given amount of time ("rate limiting")',
    "URI is too long",
    "URI no longer exists and has been permanently removed",
    "URI not available in preferred format",
    "You must authenticate with this proxy before proceeding",
    "You must use proxy specified in Location to access this resource",
)
# How isik._internal.translation's functions are imported and called throughout the package.
TRANSLATORS = {"_", "gettext", "gettext_lazy", "lazy_format"}

HEADER = """# Every message isik marks for translation. Generated by `python -m tests.translation_catalog` -
# don't edit by hand. Django projects: merge into your project's django.po (msgmerge). Without
# Django: compile a copy per language to isik.mo and gettext.bindtextdomain("isik", ...).
msgid ""
msgstr ""
"Project-Id-Version: isik\\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"
"Last-Translator: \\n"
"Language-Team: \\n"
"Language: \\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"""


def called_name(call):
    func = call.func
    return func.id if isinstance(func, ast.Name) else func.attr if isinstance(func, ast.Attribute) else None


def translation_calls(tree):
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and called_name(node) in TRANSLATORS and node.args:
            yield node


def messages():
    """msgid -> sorted locations, for every literal passed to a translation function in the package -
    plus the stdlib HTTPStatus descriptions, which http_exceptions translates when it renders them."""
    found = {}
    for description in HTTP_STATUS_DESCRIPTIONS:
        found.setdefault(description, []).append("http.HTTPStatus")
    for path in sorted(PACKAGE.rglob("*.py")):
        tree = ast.parse(path.read_text(), filename=str(path))
        for call in translation_calls(tree):
            first = call.args[0]
            if isinstance(first, ast.Constant) and isinstance(first.value, str):
                found.setdefault(first.value, []).append(f"{path.relative_to(ROOT)}:{call.lineno}")
    return found


def quote(text):
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t").replace("\n", "\\n")
    return f'"{escaped}"'


def render():
    entries = [HEADER]
    for msgid, locations in sorted(messages().items()):
        lines = [f"#: {location}" for location in locations]
        if "%(" in msgid:
            lines.append("#, python-format")
        lines += [f"msgid {quote(msgid)}", 'msgstr ""']
        entries.append("\n".join(lines) + "\n")
    return "\n".join(entries)


if __name__ == "__main__":
    CATALOG.parent.mkdir(parents=True, exist_ok=True)
    CATALOG.write_text(render())
    print(f"wrote {len(messages())} messages to {CATALOG.relative_to(ROOT)}", file=sys.stderr)
