# Generated by Django 6.0.3 on 2026-10-02 22:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import django_lifecycle.mixins
import isik.django.apps.common.skippable_validators.mixin
import isik.django.apps.feedback.bookmarks._bookmarks
import isik.django.apps.feedback.comments._comments
import isik.django.apps.feedback.comments.tiptap
import isik.django.apps.feedback.notes._notes
import isik.django.apps.feedback.votes._votes
import isik.django.apps.tags.tags
import isik.django.apps.templated_fields.delimiters
import isik.django.apps.templated_fields.field
import isik.django.apps.templated_fields.policy
import pgtrigger.compiler
import pgtrigger.migrations
import tests.testapp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('title', models.CharField(max_length=100)),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleCommentsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
                ('body', models.JSONField(db_comment='The comment, as a Tiptap document.', help_text='The comment, as a Tiptap document.', validators=[isik.django.apps.feedback.comments.tiptap.TiptapValidator(max_length=280, min_length=1, schema_path=None)])),
            ],
        ),
        migrations.CreateModel(
            name='CleanedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, validators=[tests.testapp.models.positive_only])),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('body', models.CharField(max_length=200)),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContextTrackedWidget',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContextTrackedWidgetEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('actor_schema', models.TextField(null=True)),
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiVoteHost',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MultiVoteHostHelpfulnessVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
                ('value', models.SmallIntegerField(choices=[(1, 'up'), (-1, 'down')], db_comment='1 for an upvote, -1 for a downvote.', help_text='1 for an upvote, -1 for a downvote.')),
            ],
        ),
        migrations.CreateModel(
            name='MultiVoteHostUpvotesVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
                ('value', models.SmallIntegerField(choices=[(1, 'up'), (-1, 'down')], db_comment='1 for an upvote, -1 for a downvote.', help_text='1 for an upvote, -1 for a downvote.')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('body', models.CharField(max_length=200)),
                ('target_object_id', models.UUIDField(db_comment='The primary key of the target object.', help_text='The primary key of the target object.')),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('title', models.CharField(max_length=100)),
            ],
            bases=(isik.django.apps.tags.tags.TaggableMixin, isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostBookmarksBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
                ('body', models.TextField(db_comment="The comment's text.", help_text="The comment's text.", validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentsCommentVotesVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
                ('value', models.SmallIntegerField(choices=[(1, 'up'), (-1, 'down')], db_comment='1 for an upvote, -1 for a downvote.', help_text='1 for an upvote, -1 for a downvote.')),
            ],
        ),
        migrations.CreateModel(
            name='PostLabelsObjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
            ],
        ),
        migrations.CreateModel(
            name='PostLabelsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
                ('name', models.CharField(db_comment="The tag's name, unique in its pool.", help_text="The tag's name, unique in its pool.", max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.-]*$', 'Tags can only contain letters, numbers, - and _.')])),
            ],
        ),
        migrations.CreateModel(
            name='PostNotesNote',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('body', models.TextField(db_comment="The note's text.", help_text="The note's text.")),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostTopicsObjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
            ],
        ),
        migrations.CreateModel(
            name='PostTopicsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
                ('name', models.CharField(db_comment="The tag's name, unique in its pool.", help_text="The tag's name, unique in its pool.", max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.-]*$', 'Tags can only contain letters, numbers, - and _.')])),
            ],
        ),
        migrations.CreateModel(
            name='PostVotesVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the row was created.', help_text='When the row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the row last changed.', help_text='When the row last changed.')),
                ('value', models.SmallIntegerField(choices=[(1, 'up'), (-1, 'down')], db_comment='1 for an upvote, -1 for a downvote.', help_text='1 for an upvote, -1 for a downvote.')),
            ],
        ),
        migrations.CreateModel(
            name='Recorder',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, default='', max_length=100)),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('label', models.CharField(max_length=100)),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaggedWidget',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TemplatedPost',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('title', models.CharField(max_length=100)),
                ('default_text', isik.django.apps.templated_fields.field.TemplateTextField(available=tests.testapp.models.default_text_context, blank=True, delimiters=isik.django.apps.templated_fields.delimiters.TemplateDelimiters(block_end_string='%}', block_start_string='{%', comment_end_string='#}', comment_start_string='{#', variable_end_string='}}', variable_start_string='{{'), policy=isik.django.apps.templated_fields.policy.TemplatePolicy(allowed_filters=None, allowed_tests=None, features=frozenset([isik.django.apps.templated_fields.policy.TemplateFeature['CONDITIONAL'], isik.django.apps.templated_fields.policy.TemplateFeature['FILTERS'], isik.django.apps.templated_fields.policy.TemplateFeature['FOR_LOOP'], isik.django.apps.templated_fields.policy.TemplateFeature['TESTS']]), max_loop_iterations=1000, max_render_length=10000, max_source_length=10000), undefined='strict')),
                ('greeting', isik.django.apps.templated_fields.field.TemplateCharField(available=tests.testapp.models.default_text_context, blank=True, delimiters=isik.django.apps.templated_fields.delimiters.TemplateDelimiters(block_end_string='%}', block_start_string='{%', comment_end_string='#}', comment_start_string='{#', variable_end_string='}}', variable_start_string='{{'), max_length=200, policy=isik.django.apps.templated_fields.policy.TemplatePolicy(allowed_filters=None, allowed_tests=None, features=frozenset([]), max_loop_iterations=1000, max_render_length=10000, max_source_length=10000), undefined='strict')),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TimestampedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('text', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0, validators=[tests.testapp.models.positive_only])),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WidgetEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0, validators=[tests.testapp.models.positive_only])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WidgetProfile',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('bio', models.CharField(blank=True, default='', max_length=200)),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WidgetSettings',
            fields=[
                ('id', models.UUIDField(db_comment='A random identifier, assigned when the row is created.', db_index=True, default=uuid.uuid4, editable=False, help_text='A random identifier, assigned when the row is created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('bio', models.CharField(blank=True, default='', max_length=200)),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WidgetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            bases=(isik.django.apps.feedback.votes._votes.UserVoteMixin, isik.django.apps.feedback.bookmarks._bookmarks.UserBookmarkMixin, isik.django.apps.feedback.notes._notes.UserNoteMixin, isik.django.apps.feedback.comments._comments.UserCommentMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='article',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='bc5576a514f08d019a044e9a79bd96b4a2f35b16', operation='UPDATE', pgid='pgtrigger_protect_created_at_da411', table='testapp_article', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='article',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='0490d7d21256f25a3655a6be0b5fbc448adb3e40', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_2d093', table='testapp_article', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='articlecommentscomment',
            name='target',
            field=models.ForeignKey(db_comment='The Article this comment is on.', help_text='The Article this comment is on.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testapp.article'),
        ),
        migrations.AddField(
            model_name='articlecommentscomment',
            name='user',
            field=models.ForeignKey(db_comment='Who wrote this comment.', help_text='Who wrote this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidget',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='a08ca046d8498e7ea1795c775bab81daf39ff38f', operation='UPDATE', pgid='pgtrigger_protect_created_at_b5b0c', table='testapp_contexttrackedwidget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidget',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='3600db43d250c1e9f87ee57fca01f87d1d3ca588', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_7c3b7', table='testapp_contexttrackedwidget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidget',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "testapp_contexttrackedwidgetevent" ("created_at", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='cdb59274424bc0dae17dd32803860ea55cc10d11', operation='INSERT', pgid='pgtrigger_insert_insert_f0d6f', table='testapp_contexttrackedwidget', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidget',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "testapp_contexttrackedwidgetevent" ("created_at", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='fe3edf84b0130679a1f6d78b2caeffa976e3f553', operation='UPDATE', pgid='pgtrigger_update_update_53041', table='testapp_contexttrackedwidget', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidget',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "testapp_contexttrackedwidgetevent" ("created_at", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (OLD."created_at", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at"); RETURN NULL;', hash='043d5acd5dfe03cbdecbbecea737322c3c7eeb9b', operation='DELETE', pgid='pgtrigger_delete_delete_e0a03', table='testapp_contexttrackedwidget', when='AFTER')),
        ),
        migrations.AddField(
            model_name='contexttrackedwidgetevent',
            name='actor',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contexttrackedwidgetevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='contexttrackedwidgetevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='testapp.contexttrackedwidget'),
        ),
        migrations.AddField(
            model_name='contexttrackedwidgetevent',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='multivotehost',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='389a02a5521ebfa0f6bb123c74c635e349fe5e5e', operation='UPDATE', pgid='pgtrigger_protect_created_at_eb706', table='testapp_multivotehost', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='multivotehost',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='d4d011909c444309523e3f73b6d001aab5cd3061', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_f9b7e', table='testapp_multivotehost', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='multivotehosthelpfulnessvote',
            name='target',
            field=models.ForeignKey(db_comment='The MultiVoteHost this vote is on.', help_text='The MultiVoteHost this vote is on.', on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness', to='testapp.multivotehost'),
        ),
        migrations.AddField(
            model_name='multivotehosthelpfulnessvote',
            name='user',
            field=models.ForeignKey(db_comment='Who cast this vote.', help_text='Who cast this vote.', on_delete=django.db.models.deletion.CASCADE, related_name='multi_host_helpfulness', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multivotehostupvotesvote',
            name='target',
            field=models.ForeignKey(db_comment='The MultiVoteHost this vote is on.', help_text='The MultiVoteHost this vote is on.', on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='testapp.multivotehost'),
        ),
        migrations.AddField(
            model_name='multivotehostupvotesvote',
            name='user',
            field=models.ForeignKey(db_comment='Who cast this vote.', help_text='Who cast this vote.', on_delete=django.db.models.deletion.CASCADE, related_name='multi_host_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='target_content_type',
            field=models.ForeignKey(db_comment='The type of the target object.', help_text='The type of the target object.', limit_choices_to=models.Q(('app_label', 'testapp'), ('model', 'widget')), on_delete=django.db.models.deletion.CASCADE, related_name='note_target+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='postbookmarksbookmark',
            name='target',
            field=models.ForeignKey(db_comment='The Post bookmarked.', help_text='The Post bookmarked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='testapp.post'),
        ),
        migrations.AddField(
            model_name='postbookmarksbookmark',
            name='user',
            field=models.ForeignKey(db_comment='Who bookmarked it.', help_text='Who bookmarked it.', on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentscomment',
            name='target',
            field=models.ForeignKey(db_comment='The Post this comment is on.', help_text='The Post this comment is on.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testapp.post'),
        ),
        migrations.AddField(
            model_name='postcommentscomment',
            name='user',
            field=models.ForeignKey(db_comment='Who wrote this comment.', help_text='Who wrote this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentscommentvotesvote',
            name='target',
            field=models.ForeignKey(db_comment='The PostCommentsComment this vote is on.', help_text='The PostCommentsComment this vote is on.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='testapp.postcommentscomment'),
        ),
        migrations.AddField(
            model_name='postcommentscommentvotesvote',
            name='user',
            field=models.ForeignKey(db_comment='Who cast this vote.', help_text='Who cast this vote.', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlabelsobjecttag',
            name='target',
            field=models.ForeignKey(db_comment='The Post tagged.', help_text='The Post tagged.', on_delete=django.db.models.deletion.CASCADE, related_name='label_object_tags', to='testapp.post'),
        ),
        migrations.AddField(
            model_name='postlabelsobjecttag',
            name='tag',
            field=models.ForeignKey(db_comment='The tag applied.', help_text='The tag applied.', on_delete=django.db.models.deletion.CASCADE, to='testapp.postlabelstag'),
        ),
        migrations.AddField(
            model_name='post',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Tags from this pool.', related_name='posts_with_label', through='testapp.PostLabelsObjectTag', to='testapp.postlabelstag'),
        ),
        migrations.AddField(
            model_name='postnotesnote',
            name='target',
            field=models.ForeignKey(db_comment='The Post this note is on.', help_text='The Post this note is on.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='testapp.post'),
        ),
        migrations.AddField(
            model_name='postnotesnote',
            name='user',
            field=models.ForeignKey(db_comment='Who wrote this note.', help_text='Who wrote this note.', on_delete=django.db.models.deletion.CASCADE, related_name='post_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posttopicsobjecttag',
            name='target',
            field=models.ForeignKey(db_comment='The Post tagged.', help_text='The Post tagged.', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='testapp.post'),
        ),
        migrations.AddField(
            model_name='posttopicsobjecttag',
            name='tag',
            field=models.ForeignKey(db_comment='The tag applied.', help_text='The tag applied.', on_delete=django.db.models.deletion.CASCADE, to='testapp.posttopicstag'),
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Tags from this pool.', related_name='posts_with_topic', through='testapp.PostTopicsObjectTag', to='testapp.posttopicstag'),
        ),
        migrations.AddField(
            model_name='postvotesvote',
            name='target',
            field=models.ForeignKey(db_comment='The Post this vote is on.', help_text='The Post this vote is on.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='testapp.post'),
        ),
        migrations.AddField(
            model_name='postvotesvote',
            name='user',
            field=models.ForeignKey(db_comment='Who cast this vote.', help_text='Who cast this vote.', on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='recorder',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='0f84d16df8cb88039009fded461461ccbba8917e', operation='UPDATE', pgid='pgtrigger_protect_created_at_5eeef', table='testapp_recorder', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='recorder',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='e2102c50ce07df44be444e598fb8fcacaeb88497', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_f56ed', table='testapp_recorder', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tag',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='d0e5c6c70c7e923e9c5e55738fb1134c9ce54423', operation='UPDATE', pgid='pgtrigger_protect_created_at_3f142', table='testapp_tag', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tag',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='d8c8ed27c85c9813be998c7cdc9263d61c4d6148', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_93f19', table='testapp_tag', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='templatedpost',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='2504c3de01edbd1cd271aa1984be4ea4540d4a66', operation='UPDATE', pgid='pgtrigger_protect_created_at_56231', table='testapp_templatedpost', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='templatedpost',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='912f6894d706cd0a91f4d261ccd1025f4b1c41dd', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_56902', table='testapp_templatedpost', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='timestampednote',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='790588cf892dce06da95422f96f37eef5f68fc71', operation='UPDATE', pgid='pgtrigger_protect_created_at_229f5', table='testapp_timestampednote', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='timestampednote',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='0805f819bb8ffc4d1dd1322d007ab276de58f453', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_76678', table='testapp_timestampednote', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='widget',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='testapp.widget'),
        ),
        migrations.AddField(
            model_name='widgetevent',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='widgetevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='widgetevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='testapp.widget'),
        ),
        migrations.AddField(
            model_name='widgetprofile',
            name='widget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='testapp.widget'),
        ),
        migrations.AddField(
            model_name='widgetsettings',
            name='widget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='testapp.widget'),
        ),
        migrations.AddField(
            model_name='widgettag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tag'),
        ),
        migrations.AddField(
            model_name='widgettag',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.widget'),
        ),
        migrations.AddField(
            model_name='taggedwidget',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_widgets', through='testapp.WidgetTag', to='testapp.tag'),
        ),
        migrations.AddIndex(
            model_name='contexttrackedwidgetevent',
            index=models.Index(fields=['tenant', 'actor'], name='ctx_widget_tenant_actor_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidgetevent',
            trigger=pgtrigger.compiler.Trigger(name='stamp_context_fields', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW."actor_id" = (NULLIF(current_setting(\'pghistory.context_metadata\', true), \'\')::jsonb ->> \'user\')::bigint;\nNEW."actor_schema" = (NULLIF(current_setting(\'pghistory.context_metadata\', true), \'\')::jsonb ->> \'schema\')::text;\nNEW."tenant_id" = (NULLIF(current_setting(\'pghistory.context_metadata\', true), \'\')::jsonb ->> \'organization\')::bigint;\nRETURN NEW;', hash='460d6e7b3bd974a59463c2107ddeae9a95504bf3', operation='INSERT', pgid='pgtrigger_stamp_context_fields_44080', table='testapp_contexttrackedwidgetevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='multivotehosthelpfulnessvote',
            constraint=models.UniqueConstraint(fields=('target', 'user'), name='unique_multivotehosthelpfulnessvote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='multivotehostupvotesvote',
            constraint=models.UniqueConstraint(fields=('target', 'user'), name='unique_multivotehostupvotesvote_per_user'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='f114b756f39911bdf692a02a106a542756b98470', operation='UPDATE', pgid='pgtrigger_protect_created_at_26349', table='testapp_note', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='678e2938a84f3f17a18ddb0f3f6e66796ce49490', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_21c99', table='testapp_note', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='postbookmarksbookmark',
            constraint=models.UniqueConstraint(fields=('target', 'user'), name='unique_postbookmarksbookmark_per_user'),
        ),
        migrations.AddConstraint(
            model_name='postcommentscommentvotesvote',
            constraint=models.UniqueConstraint(fields=('target', 'user'), name='unique_postcommentscommentvotesvote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='postlabelsobjecttag',
            constraint=models.UniqueConstraint(fields=('tag', 'target'), name='unique_postlabelsobjecttag'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='postnotesnote',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='ac6fd96cd486d23f0a786ce254a909fefdb4352a', operation='UPDATE', pgid='pgtrigger_protect_created_at_e561a', table='testapp_postnotesnote', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='postnotesnote',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='138361415b2c11935ea2cc44cfb8a41c885ab9c5', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_78f67', table='testapp_postnotesnote', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='posttopicsobjecttag',
            constraint=models.UniqueConstraint(fields=('tag', 'target'), name='unique_posttopicsobjecttag'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='6186fe17504e1ce5ddd1dad17c29010556f2d2f3', operation='UPDATE', pgid='pgtrigger_protect_created_at_93f33', table='testapp_post', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='e41a59640f4f3e3ea1e5cb701081a63103c66298', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_9ebd9', table='testapp_post', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='postvotesvote',
            constraint=models.UniqueConstraint(fields=('target', 'user'), name='unique_postvotesvote_per_user'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widget',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='95fda933b8634f48040449a20029d9eb0c205bfb', operation='UPDATE', pgid='pgtrigger_protect_created_at_ee339', table='testapp_widget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widget',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='86ef92fd4b9218263cdfa96f27c29a203b49a0c8', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_2957b', table='testapp_widget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widget',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "testapp_widgetevent" ("count", "created_at", "id", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."count", NEW."created_at", NEW."id", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='4ef3f9454cd61a16038f592b930cfda1995b7ce8', operation='INSERT', pgid='pgtrigger_insert_insert_d188c', table='testapp_widget', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widget',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "testapp_widgetevent" ("count", "created_at", "id", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."count", NEW."created_at", NEW."id", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='3675fc1053be70c662fb007785150953849558c2', operation='UPDATE', pgid='pgtrigger_update_update_ae255', table='testapp_widget', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widget',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "testapp_widgetevent" ("count", "created_at", "id", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (OLD."count", OLD."created_at", OLD."id", OLD."name", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at"); RETURN NULL;', hash='13c30efb4877a32214bfb73e5347d5df32158a12', operation='DELETE', pgid='pgtrigger_delete_delete_5e6aa', table='testapp_widget', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comment',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='6ca5cb851f3a0e42cd66ecf68ffd5d6cf72b0de0', operation='UPDATE', pgid='pgtrigger_protect_created_at_f45d5', table='testapp_comment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comment',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='7dd14d3d7096896c6a76d7f27e53173bc898be33', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_3b550', table='testapp_comment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widgetprofile',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='00c6891011f818921d6d7b509c8db6305454cbed', operation='UPDATE', pgid='pgtrigger_protect_created_at_83481', table='testapp_widgetprofile', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widgetprofile',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='1f5cebf610dd4125cb83b27cf9ac885a5dd2f898', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_48c3d', table='testapp_widgetprofile', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widgetsettings',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='35bc0d8fbdb20cacb70405929044f6208de0dbbb', operation='UPDATE', pgid='pgtrigger_protect_created_at_fb07d', table='testapp_widgetsettings', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widgetsettings',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='92921b71c13cdc1acad0b061c049cbb70bfd52ef', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_8b7e2', table='testapp_widgetsettings', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taggedwidget',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='c15a464feb121410872e9f9e6b58500463e92391', operation='UPDATE', pgid='pgtrigger_protect_created_at_6e8be', table='testapp_taggedwidget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taggedwidget',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='fe84bc0dd2f78e2fdd31c26b9efecd56bdc5bebb', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_56bb5', table='testapp_taggedwidget', when='BEFORE')),
        ),
    ]
