# Generated by Django 6.0.3 on 2026-07-22 00:44

import django_lifecycle.mixins
import isik.django.apps.common.skippable_validators.mixin
import isik.django.apps.templated_fields.delimiters
import isik.django.apps.templated_fields.field
import isik.django.apps.templated_fields.policy
import tests.testapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatedPost',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=100)),
                ('default_text', isik.django.apps.templated_fields.field.TemplateTextField(available=tests.testapp.models.default_text_context, blank=True, delimiters=isik.django.apps.templated_fields.delimiters.TemplateDelimiters(block_end_string='%}', block_start_string='{%', comment_end_string='#}', comment_start_string='{#', variable_end_string='}}', variable_start_string='{{'), policy=isik.django.apps.templated_fields.policy.TemplatePolicy(allowed_filters=None, allowed_tests=None, features=frozenset([isik.django.apps.templated_fields.policy.TemplateFeature['CONDITIONAL'], isik.django.apps.templated_fields.policy.TemplateFeature['FILTERS'], isik.django.apps.templated_fields.policy.TemplateFeature['FOR_LOOP'], isik.django.apps.templated_fields.policy.TemplateFeature['TESTS']]), max_loop_iterations=1000, max_render_length=10000, max_source_length=10000), undefined='strict')),
                ('greeting', isik.django.apps.templated_fields.field.TemplateCharField(available=tests.testapp.models.default_text_context, blank=True, delimiters=isik.django.apps.templated_fields.delimiters.TemplateDelimiters(block_end_string='%}', block_start_string='{%', comment_end_string='#}', comment_start_string='{#', variable_end_string='}}', variable_start_string='{{'), max_length=200, policy=isik.django.apps.templated_fields.policy.TemplatePolicy(allowed_filters=None, allowed_tests=None, features=frozenset([]), max_loop_iterations=1000, max_render_length=10000, max_source_length=10000), undefined='strict')),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
