# Generated by Django 6.0.3 on 2026-10-08 18:11

import isik.django.apps.common.db.constraints
import tests.testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanednote',
            name='kind',
            field=models.CharField(choices=[('bolt', 'Bolt'), ('nut', 'Nut')], default='bolt', max_length=16),
        ),
        migrations.AddField(
            model_name='cleanednote',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True, validators=[tests.testapp.models.not_in_the_future]),
        ),
        migrations.AlterField(
            model_name='widget',
            name='count',
            field=models.IntegerField(default=0, validators=[isik.django.apps.common.db.constraints.python_only_validator(tests.testapp.models.positive_only, reason='SkipFieldValidators lifts this one, and a CHECK constraint cannot be lifted.')]),
        ),
        migrations.AlterField(
            model_name='widgetevent',
            name='count',
            field=models.IntegerField(default=0, validators=[isik.django.apps.common.db.constraints.python_only_validator(tests.testapp.models.positive_only, reason='SkipFieldValidators lifts this one, and a CHECK constraint cannot be lifted.')]),
        ),
        migrations.AddConstraint(
            model_name='cleanednote',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 0)), name='testapp_cleanednote_count_validators'),
        ),
        migrations.AddConstraint(
            model_name='cleanednote',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['bolt', 'nut'])), name='testapp_cleanednote_kind_choices'),
        ),
    ]
