# Generated by Django 6.0.3 on 2026-07-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_templatedpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="recorder",
            name="slug",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
