# Generated by Django 6.0.3 on 2026-08-03 01:36

import django.db.models.deletion
import django_lifecycle.mixins
import isik.django.apps.common.skippable_validators.mixin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_recorder_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('bio', models.CharField(blank=True, default='', max_length=200)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='testapp.widget')),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
