# Generated by Django 6.0.3 on 2026-08-28 13:31

import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_widgetsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='multivotehost',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='multivotehost',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='postnotesnote',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='postnotesnote',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='recorder',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='recorder',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='taggedwidget',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='taggedwidget',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='templatedpost',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='templatedpost',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='widgetevent',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='widgetevent',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='widgetprofile',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='widgetprofile',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='widgetsettings',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='widgetsettings',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='article',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='bc5576a514f08d019a044e9a79bd96b4a2f35b16', operation='UPDATE', pgid='pgtrigger_protect_created_at_da411', table='testapp_article', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='article',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='0490d7d21256f25a3655a6be0b5fbc448adb3e40', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_2d093', table='testapp_article', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comment',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='6ca5cb851f3a0e42cd66ecf68ffd5d6cf72b0de0', operation='UPDATE', pgid='pgtrigger_protect_created_at_f45d5', table='testapp_comment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comment',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='7dd14d3d7096896c6a76d7f27e53173bc898be33', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_3b550', table='testapp_comment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='multivotehost',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='389a02a5521ebfa0f6bb123c74c635e349fe5e5e', operation='UPDATE', pgid='pgtrigger_protect_created_at_eb706', table='testapp_multivotehost', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='multivotehost',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='d4d011909c444309523e3f73b6d001aab5cd3061', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_f9b7e', table='testapp_multivotehost', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='f114b756f39911bdf692a02a106a542756b98470', operation='UPDATE', pgid='pgtrigger_protect_created_at_26349', table='testapp_note', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='678e2938a84f3f17a18ddb0f3f6e66796ce49490', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_21c99', table='testapp_note', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='6186fe17504e1ce5ddd1dad17c29010556f2d2f3', operation='UPDATE', pgid='pgtrigger_protect_created_at_93f33', table='testapp_post', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='e41a59640f4f3e3ea1e5cb701081a63103c66298', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_9ebd9', table='testapp_post', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='postnotesnote',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='ac6fd96cd486d23f0a786ce254a909fefdb4352a', operation='UPDATE', pgid='pgtrigger_protect_created_at_e561a', table='testapp_postnotesnote', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='postnotesnote',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='138361415b2c11935ea2cc44cfb8a41c885ab9c5', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_78f67', table='testapp_postnotesnote', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='recorder',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='0f84d16df8cb88039009fded461461ccbba8917e', operation='UPDATE', pgid='pgtrigger_protect_created_at_5eeef', table='testapp_recorder', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='recorder',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='e2102c50ce07df44be444e598fb8fcacaeb88497', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_f56ed', table='testapp_recorder', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tag',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='d0e5c6c70c7e923e9c5e55738fb1134c9ce54423', operation='UPDATE', pgid='pgtrigger_protect_created_at_3f142', table='testapp_tag', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tag',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='d8c8ed27c85c9813be998c7cdc9263d61c4d6148', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_93f19', table='testapp_tag', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taggedwidget',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='c15a464feb121410872e9f9e6b58500463e92391', operation='UPDATE', pgid='pgtrigger_protect_created_at_6e8be', table='testapp_taggedwidget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taggedwidget',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='fe84bc0dd2f78e2fdd31c26b9efecd56bdc5bebb', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_56bb5', table='testapp_taggedwidget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='templatedpost',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='2504c3de01edbd1cd271aa1984be4ea4540d4a66', operation='UPDATE', pgid='pgtrigger_protect_created_at_56231', table='testapp_templatedpost', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='templatedpost',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='912f6894d706cd0a91f4d261ccd1025f4b1c41dd', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_56902', table='testapp_templatedpost', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widget',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='95fda933b8634f48040449a20029d9eb0c205bfb', operation='UPDATE', pgid='pgtrigger_protect_created_at_ee339', table='testapp_widget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widget',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='86ef92fd4b9218263cdfa96f27c29a203b49a0c8', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_2957b', table='testapp_widget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widgetprofile',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='00c6891011f818921d6d7b509c8db6305454cbed', operation='UPDATE', pgid='pgtrigger_protect_created_at_83481', table='testapp_widgetprofile', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widgetprofile',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='1f5cebf610dd4125cb83b27cf9ac885a5dd2f898', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_48c3d', table='testapp_widgetprofile', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widgetsettings',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='35bc0d8fbdb20cacb70405929044f6208de0dbbb', operation='UPDATE', pgid='pgtrigger_protect_created_at_fb07d', table='testapp_widgetsettings', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='widgetsettings',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='92921b71c13cdc1acad0b061c049cbb70bfd52ef', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_8b7e2', table='testapp_widgetsettings', when='BEFORE')),
        ),
    ]
