# Generated by Django 6.0.3 on 2026-08-29 15:42

import django.db.models.deletion
import django.db.models.functions.datetime
import django_lifecycle.mixins
import isik.django.apps.common.skippable_validators.mixin
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('testapp', '0006_db_maintained_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextTrackedWidget',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContextTrackedWidgetEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidget',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='a08ca046d8498e7ea1795c775bab81daf39ff38f', operation='UPDATE', pgid='pgtrigger_protect_created_at_b5b0c', table='testapp_contexttrackedwidget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidget',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.updated_at = NOW(); RETURN NEW;', hash='3600db43d250c1e9f87ee57fca01f87d1d3ca588', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_7c3b7', table='testapp_contexttrackedwidget', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidget',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "testapp_contexttrackedwidgetevent" ("created_at", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='cdb59274424bc0dae17dd32803860ea55cc10d11', operation='INSERT', pgid='pgtrigger_insert_insert_f0d6f', table='testapp_contexttrackedwidget', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidget',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "testapp_contexttrackedwidgetevent" ("created_at", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='fe3edf84b0130679a1f6d78b2caeffa976e3f553', operation='UPDATE', pgid='pgtrigger_update_update_53041', table='testapp_contexttrackedwidget', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidget',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "testapp_contexttrackedwidgetevent" ("created_at", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (OLD."created_at", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at"); RETURN NULL;', hash='043d5acd5dfe03cbdecbbecea737322c3c7eeb9b', operation='DELETE', pgid='pgtrigger_delete_delete_e0a03', table='testapp_contexttrackedwidget', when='AFTER')),
        ),
        migrations.AddField(
            model_name='contexttrackedwidgetevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contexttrackedwidgetevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='contexttrackedwidgetevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='testapp.contexttrackedwidget'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidgetevent',
            trigger=pgtrigger.compiler.Trigger(name='stamp_context_fields', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW."actor_id" = (NULLIF(current_setting(\'pghistory.context_metadata\', true), \'\')::jsonb ->> \'user\')::bigint;\nRETURN NEW;', hash='ed3d1d5c5a8a519040981aa568fffed488e73df8', operation='INSERT', pgid='pgtrigger_stamp_context_fields_44080', table='testapp_contexttrackedwidgetevent', when='BEFORE')),
        ),
    ]
