# Generated by Django 6.0.3 on 2026-08-29 17:48

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('testapp', '0007_context_tracked_widget'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='contexttrackedwidgetevent',
            name='stamp_context_fields',
        ),
        migrations.AddField(
            model_name='contexttrackedwidgetevent',
            name='actor_schema',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contexttrackedwidgetevent',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contexttrackedwidgetevent',
            name='actor',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contexttrackedwidgetevent',
            index=models.Index(fields=['tenant', 'actor'], name='ctx_widget_tenant_actor_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='contexttrackedwidgetevent',
            trigger=pgtrigger.compiler.Trigger(name='stamp_context_fields', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW."actor_id" = (NULLIF(current_setting(\'pghistory.context_metadata\', true), \'\')::jsonb ->> \'user\')::bigint;\nNEW."actor_schema" = (NULLIF(current_setting(\'pghistory.context_metadata\', true), \'\')::jsonb ->> \'schema\')::text;\nNEW."tenant_id" = (NULLIF(current_setting(\'pghistory.context_metadata\', true), \'\')::jsonb ->> \'organization\')::bigint;\nRETURN NEW;', hash='460d6e7b3bd974a59463c2107ddeae9a95504bf3', operation='INSERT', pgid='pgtrigger_stamp_context_fields_44080', table='testapp_contexttrackedwidgetevent', when='BEFORE')),
        ),
    ]
