"""
Validates Tiptap/ProseMirror JSON documents for `comments(tiptap=True)`, using `prosemirror-py`'s
real `Schema` + `Node.from_json` + `.check()` rather than a hand-rolled structural walker.
`.check()` specifically matters: `Node.from_json` alone doesn't enforce nested content rules (a
`listItem` containing a `codeBlock` would silently deserialize even where the schema forbids it),
`.check()` is what actually walks the tree and raises on that.

This module never hand-maintains its own copy of the frontend's schema. It reads one from a JSON
file at `settings.FEEDBACK_COMMENTS_TIPTAP_SCHEMA_PATH` (or a per-call `schema_path=` override),
shaped exactly like a ProseMirror schema spec minus the DOM-only parts:

    {"nodes": {"doc": {"content": "block+"},
               "paragraph": {"content": "inline*", "group": "block"},
               "text": {"group": "inline"},
               "mention": {"group": "inline", "inline": true, "atom": true, "attrs": {"id": {}}}},
     "marks": {"bold": {}, "italic": {}}}

That file is meant to be generated by the frontend build from its actual Tiptap extensions list -
the one source of truth for what documents it can produce - and dropped at the configured path.
Only `content`/`group`/`marks`/`inline`/`atom`/`attrs` (with `default`s) matter here; `parseDOM`/
`toDOM`/`renderHTML` are rendering-only and should be stripped before export. See
https://prosemirror.net/docs/guide/#schema for the content-expression syntax.
"""

import functools
import json

from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible
from prosemirror.model import Node, Schema


@functools.lru_cache
def _load_schema(schema_path):
    with open(schema_path) as f:
        spec = json.load(f)
    return Schema(spec)


def _resolve_schema_path(explicit):
    path = explicit or getattr(settings, "FEEDBACK_COMMENTS_TIPTAP_SCHEMA_PATH", None)
    if not path:
        raise ValidationError(
            "No Tiptap schema configured - set FEEDBACK_COMMENTS_TIPTAP_SCHEMA_PATH or pass schema_path= explicitly."
        )
    return path


def parse_and_check(value, *, schema_path=None):
    """
    Parses and validates `value` (a Tiptap document, as a plain dict) against the configured
    schema. Raises `django.core.exceptions.ValidationError` on anything wrong - unknown node/mark
    types, missing required attrs, invalid nesting, or a malformed shape entirely. Returns the
    parsed `prosemirror.model.Node` on success.
    """
    if not isinstance(value, dict):
        raise ValidationError("Tiptap document must be a JSON object.")
    if value.get("type") != "doc":
        raise ValidationError("Tiptap document must have a top-level type of 'doc'.")
    schema = _load_schema(_resolve_schema_path(schema_path))
    try:
        node = Node.from_json(schema, value)
        node.check()
    except Exception as exc:
        raise ValidationError(f"Invalid Tiptap document: {exc}") from exc
    return node


def get_mentions(value):
    """Returns the list of mention node `id` attrs found anywhere in `value` (a Tiptap document,
    as a plain dict) - e.g. to notify @mentioned users. Doesn't require `value` to be valid."""
    ids = []

    def walk(node):
        if not isinstance(node, dict):
            return
        if node.get("type") == "mention":
            mention_id = node.get("attrs", {}).get("id")
            if mention_id is not None:
                ids.append(mention_id)
        for child in node.get("content", []):
            walk(child)

    walk(value)
    return ids


@deconstructible
class TiptapValidator:
    """
    Model field validator for `comments(tiptap=True)` - see the module docstring for the schema
    file contract. Enforces `min_length`/`max_length` against the document's extracted plain
    text, not the raw JSON.
    """

    def __init__(self, *, min_length=None, max_length=None, schema_path=None):
        self.min_length = min_length
        self.max_length = max_length
        self.schema_path = schema_path

    def __call__(self, value):
        node = parse_and_check(value, schema_path=self.schema_path)
        text_length = len(node.text_content)
        if self.min_length is not None and text_length < self.min_length:
            raise ValidationError(f"Comment must be at least {self.min_length} characters, got {text_length}.")
        if self.max_length is not None and text_length > self.max_length:
            raise ValidationError(f"Comment must be at most {self.max_length} characters, got {text_length}.")

    def __eq__(self, other):
        return isinstance(other, TiptapValidator) and (self.min_length, self.max_length, self.schema_path) == (
            other.min_length,
            other.max_length,
            other.schema_path,
        )
